### ISSUE TITLE
Add .github templates

### ISSUE THREAD

**Issue by tonifisler** [frontend/generator-toolbox#50]
- [ ] `.github/ISSUE_TEMPLATE.md`
- [ ] `.github/PULL_REQUEST_TEMPLATE.md`

Suggestions on how to format them?
## ISSUE_TEMPLATE

``` markdown
## Description
Describe the bug precisely.

## Steps to reproduce
Describe how you can reproduce this bug. Include some screenshots and clear descriptions to help us understanding.

## TODO
- [ ] things
- [ ] to do
- [ ] to fix this bug
```
## PULL_REQUEST_TEMPLATE

Do we need one?
